#!/usr/bin/fish
set -Ux GRWSL /home/gr/grwsl/system
begin
    set -l grconfig "$GRWSL/config"
    set -l config "$HOME/.config"
    # X11 settings
    ln -sf "$grconfig/.Xresources" "$HOME/.Xresources"
    # Fish startup scripts
    rm -f $config/fish/conf.d/*.gr.fish
    
    sudo ln -sf "$grconfig/wsl.conf" "/etc/wsl.conf"
    sudo ln -sf "$grconfig/resolv.conf" "/etc/resolv.conf"
    rm -f "$config/fish/conf.d/*.gr.fish"

    for file in (status dirname)/../config/startup/*
        ln -sf $file "$config/fish/conf.d/"(basename $file)
    end


    # fonts and resources
    ln -sf "$grconfig/fonts.user.conf" "$HOME/.fonts.conf"
    ln -sf "$grconfig/.fonts" "$HOME/.fonts"
    sudo ln -sf "$grconfig/themes/cinnamon-cursor" "/usr/share/icons/cinnamon-cursor"
    sudo ln -sf "$grconfig/fonts.system.conf" "/etc/fonts/local.conf"
    
    # application config files
    set phpstorm_version "PhpStorm2021.3"
    set pycharm_version "PyCharmCE2021.3"
    ln -sf "$grconfig/app/phpstorm/phpstorm64.vmoptions" "$config/JetBrains/$phpstorm_version/phpstorm64.vmoptions"
    ln -sf "$grconfig/app/pycharm/pycharm64.vmoptions" "$config/JetBrains/$pycharm_version/pycharm64.vmoptions"

    # create symlinks to specific Windows binaries instead of allowing them all
    set winb "cmd.exe" "clip.exe" "ipconfig.exe"
    
    for bin in $winb
        ln -s "/mnt/c/Windows/System32/$bin" "$HOME/grwsl/apps/$bin"
    end
end

