#!/usr/bin/fish
set -Ux GRWSL /home/gr/grwsl/system
begin
    set -l grconfig "$GRWSL/config"
    set -l config "$HOME/.config"
    # X11 settings
    ln -sf "$grconfig/.Xresources" "$HOME/.Xresources"
    # Fish startup scripts
    rm -f $config/fish/conf.d/*.gr.fish
    
    rm -f "$config/fish/conf.d/*.gr.fish"
 
    mkdir -p ~/.config/fish/conf,d
    for file in (status dirname)/../config/startup/*.gr.fish
        ln -sf $file (realpath "$config/fish/conf.d/"(basename $file))
    end
    for file in (status dirname)/../config/functions/*.fish
        ln -sf $file (realpath "$config/fish/functions/"(basename $file))
    end


    # fonts and resources
    ln -sf "$grconfig/fonts.user.conf" "$HOME/.fonts.conf"
    ln -sf "$grconfig/.fonts" "$HOME/.fonts"
    sudo ln -sf "$grconfig/themes/cinnamon-cursor" "/usr/share/icons/cinnamon-cursor"
    sudo ln -sf "$grconfig/fonts.system.conf" "/etc/fonts/local.conf"
    
    # application config files
    set phpstorm_version "PhpStorm2021.3"
    set pycharm_version "PyCharmCE2021.3"
    ln -sf "$grconfig/app/phpstorm/phpstorm64.vmoptions" "$config/JetBrains/$phpstorm_version/phpstorm64.vmoptions"
    ln -sf "$grconfig/app/pycharm/pycharm64.vmoptions" "$config/JetBrains/$pycharm_version/pycharm64.vmoptions"

    # create symlinks to specific Windows binaries instead of allowing them all
    set winb "cmd.exe" "clip.exe" "ipconfig.exe" "mklink.exe"
    
    for bin in $winb
        ln -sf "/mnt/c/Windows/System32/$bin" "$HOME/grwsl/apps/$bin"
    end
    sudo ln -sf "/mnt/c/Users/GregRosenbaum/AppData/Local/Programs/Microsoft VS Code/bin/code" /usr/bin/code
    sudo ln -sf "$GRWSL/tools/grstart" /usr/bin/grstart
end

