#!/usr/bin/fish
begin
    set SCRIPT_DIR /home/gr/scripts
    set new_cwd $argv[1]
    echo "$new_cwd" > ~/a.x
    if string match -e "\\" "$new_cwd"
        set new_cwd (wslpath -u "$new_cwd")
    else if test "~" = "$new_cwd"
        set new_cwd "$HOME"
    end
    if not string match _NONE_ "$new_cwd"
        cd "$new_cwd"
    end
    fish --login -c $argv[2..-1]
end
