#!/bin/bash
ssh() {
  gcloud compute ssh $@
}

k8s_creds() {
  local cluster="$1"
  if ! [[ -z "$ZONE" ]]; then
    cur_zone="$(zzone "$ZONE")"
  fi
  gcloud container clusters get-credentials "$cluster" $cur_zone
}

img() {
  echo "eu.gcr.io/explorerv0-220316/$1"
}

zone() {
  case "$1" in
  eu)
    echo "europe-west4-a"
    ;;
  us)
    echo "us-central1-c"
    ;;
  ca)
    echo "northamerica-northeast1-a"
    ;;
  *)
    "Unknown zone $1." >&2
    exit 1
    ;;
  esac
}

zzone() {
  echo "--zone=$(zone "$1") --project=explorerv0-220316"
}

if declare -f "$1" > /dev/null; then
  "$@"
else
  gcloud $@
fi
